### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by akalendarov** [consultit/Ely#1]
Hello. I'm trying to install your application on OS Ubuntu 14.04.
At first I ran "autoconf". But after, while "./configure" is working, errors appear.

./configure: line 2220: AM_INIT_AUTOMAKE: command not found
./configure: line 2221: syntax error near unexpected token `2.2'
./configure: line 2221: `LT_PREREQ(2.2)'

Can you help me please?

**Comment by consultit** [comment]
look ad Ely/doc/INSTALL.Ely
